apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-server
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.appscode.com/stable/'
    targetRevision: v0.1.1
    chart: identity-server
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
